### ISSUE TITLE
Add ID field to message object

### ISSUE THREAD

**Issue by zephyr1999** [oudalab/bismol#1]
The first collumn of the neel data is actually an id. Tweets also have a unique id, see:

http://tkang.blogspot.com/2011/01/tweepy-twitter-api-status-object.html

so maybe it would be a good idea to have that in the message object? Idk, just an idea.

**Comment by cegme** [comment]
I agree, a message id is a standard enough to add it to the message class. We can also have a dictionary for any other field that people want to add.
